# Config
# ========================================================================================

# Uncomment and set the URL of your site (with protocol, e.g. `https://`)
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.

url: "http://127.0.0.1:4000" # Localhost URL for local development github.com/ReallyCoolData/RolloTheGreat.github.io

# Uncomment and set the "base URL" of your site.
# When your site is in a subdirectory, set to `/<name of directory>`,
# with a leading `/` but no trailing `/`. Use the empty string '' otherwise.
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.

baseurl: "" #should be empty for local development

#github_username: carlos 

# General settings
# ---------------------------------------------------------------------------------------
theme: jekyll-theme-hydejack

title: Rollo The Great - A dog's life!

email: RolloTheGreatDog@outlook.com

description: >- # this is a comment means ignore until "baseurl:"
  This website features Rollo; a Poodle-Rottweiler mix aka a Roddle or a RottiPoo! Get to know his puppy-to-adult trials and tribulations and follow all of his adventures.


# Customization
#----------------------------------------------------------------------------

# Sidebar image and theme color of the site
#accent_image: /assets/img/foggy-forest.jpg
accent_image: /assets/images/Rollo.jpg
accent_color: rgb(79,125,190)

# Add links to the sidebar
menu:
 - title: Blog
   url: /blog/
 - title: About
   url: /about/
