# Config
# ========================================================================================

# Uncomment and set the URL of your site (with protocol, e.g. `https://`)
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.

url: "http://127.0.0.1:4000" # Localhost URL for local development github.com/ReallyCoolData/RolloTheGreat.github.io

# Uncomment and set the "base URL" of your site.
# When your site is in a subdirectory, set to `/<name of directory>`,
# with a leading `/` but no trailing `/`. Use the empty string '' otherwise.
# NOTE: You don't need to provide this property when hosting on GitHub Pages or Netlify.

baseurl: "" #should be empty for local development

#github_username: carlos 


# Theme
# ---------------------------------------------------------------------------------------

# This will use the gem `jekyll-theme-hydejack`, as defined in the sibling `Gemfile`.
#theme: jekyll-theme-hydejack
remote_theme: hydecorp/hydejack@v9.2.1

# You can uncomment `theme` above and replace it with `remote_theme` here iff you are using the 
# `jekyll-remote-theme` plugin (which is the case when using the legacy GitHub Pages pipeline).
# This will fetch the `v9` branch of the public Hydejack repository on GitHub.
# remote_theme: hydecorp/hydejack@v9

# OTHER THEMES
#theme: jekyll-theme-cayman
#remote_theme: pages-theme/cayman@v0.2.0

# General settings
# ---------------------------------------------------------------------------------------
title: Rollo The Great - A dog's life!

email: RolloTheGreatDog@outlook.com

description: >- # this is a comment means ignore until "baseurl:"
  This website features Rollo; a Poodle-Rottweiler mix aka a Roddle or a RottiPoo! Get to know his puppy-to-adult trials and tribulations and follow all of his adventures.


# A shorter description for the sidebar.
tagline:               The wonderful world of Rollo, the Roddle!

# A list of keywords for your blog
keywords:              [Poodle Rottweiler Roddle Rottiepoo dog Rollo]

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/img/logo.png

# Add links to the sidebar
menu:
 - title: Blog
   url: /
 - title: About
   url: /about/

# Customization
#----------------------------------------------------------------------------

# Sidebar image and theme color of the site
#accent_image: /assets/img/foggy-forest.jpg
accent_image: /assets/images/Rollo.jpg
accent_color: rgb(79,125,190)


# plugins
plugins:
# - jekyll-remote-theme
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-include-cache
  - jekyll-last-modified-at

paginate: 10
paginate_path: "/blog/page:num/"
